baseURL = 'https://final-jose-a1.netlify.app'
languageCode = 'en-us'
title = 'Home'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[markup.goldmark.renderer]
  unsafe = true


MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"



[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'page'


googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/trident_favicon.jpg"
  site_logo = ""
  headdescription = "Promoting and teaching Ashtanga Yoga in Eastern Kentucky.  Ashtanga, pranayama, Sanskrit, meditation, Georgetown Kentucky."
  #facebook = "https://www.facebook.com/joseacunay/photos_by"
  #instagram = "https://www.instagram.com/joseacunay/
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/shiva_moon_landscape-2.jpg"
  recent_posts_number = 2
  cover_dimming_class = "bg-black-00"
  site_header_text_background_color = "rgba(50, 50, 50, 0.7);"
  page_header_text_background_color = "rgba(50, 50, 50, 0.7)"
  custom_css = ["css/custom.css"]

[params.ananke.social.follow]
  new_window_icon = false
  networks = [
    "facebook",
    "instagram"
  ]

[params.ananke.social.instagram]
username = "joseacunay"

[params.ananke.social.facebook]
profilelink = "https://www.facebook.com/joseacunay/photos_by"

[params.ananke.social.email]
profilelink = "mailto:jacuna_yepes@georgetowncollege.edu"


[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1


[[menu.main]]
  identifier = "about"
  name = "About Jose"
  url = "/about/"
  weight = 2 


[[menu.main]]
  identifier = "articles"
  name = "Articles"
  url = "/articles/"
  weight = 3 

  [[menu.main]]
  identifier = "Blog"
  name = "Blog"
  url = "/Blog/"
  weight = 4 